#!/usr/bin/env python
# -*- coding: utf-8 -*-


__license__ = """
CPUSpeed (C)left 2008-2016, Heiko 'riot' Weinen <riot@c-base.org>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

And don't you point any lawyers at me!
Send me a postcard, if you like this software.
"""

import gtk
import gobject
import click


class CPUSpeed:
    def destroy(self, widget, data=None):
        """
        Closes down the application

        :param widget:
        :param data:
        :return:
        """
        gobject.source_remove(self.reader)
        gtk.main_quit()

    def __init__(self, args, parser):
        """
        Sets up the window, configuration and events.

        :param args: arguments parsed by parser
        :param parser: argparse.parser
        """
        self.maximum = max_frequency * base_frequency
        self.medium_high = medium_high * base_frequency
        self.medium_low = medium_low * base_frequency
        self.minimum = low * base_frequency
        self.cpucount = count
        self.refreshinterval = refresh
        self.no_labels = no_labels

        self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)

        self.reader = gobject.timeout_add(self.refreshinterval, self.read)

        #        self.window.connect("delete_event", self.delete_event)
        self.window.connect("destroy", self.destroy)

        self.window.set_border_width(2)
        self.window.set_opacity(0.25)

        tableheight = 1 if self.no_labels else 2
        labelspace = 0 if self.no_labels else 1
        self.cputable = gtk.Table(tableheight, self.cpucount + labelspace, True)
        self.window.add(self.cputable)


        if not self.no_labels:
            self.speedfreq = gtk.Label("N/A")
            self.speedlabel = gtk.Label("AVG")
            self.cputable.attach(self.speedfreq, 0, 1, 0, 1)
            self.cputable.attach(self.speedlabel, 0, 1, 1, 2)

        self.minimal_frequency = 9999
        self.maximal_frequency = 0000

        self.cpulabels = []
        self.eventboxes = []

        for cpunumber in range(self.cpucount):
            cpufreq = gtk.Label(" ")
            eventbox = gtk.EventBox()
            eventbox.add(cpufreq)

            if not self.no_labels:
                cpulabel = gtk.Label("%i" % cpunumber)
                self.cputable.attach(cpulabel, cpunumber + labelspace, cpunumber + 2, 1, 2)
                self.cpulabels.append(cpufreq)
                cpulabel.show()
            
            self.cputable.attach(eventbox, cpunumber + labelspace, cpunumber + 2, 0, 1)
            self.eventboxes.append(eventbox)
            eventbox.show()
            cpufreq.show()

        if not self.no_labels:
            self.speedfreq.show()
            self.speedlabel.show()
        self.cputable.show()
        self.window.show()

    def read(self):
        """
        Reads out the kernel frequency scaler current value table,
        colorizes the bars and displays the frequencies accordingly.
        """
        speed = 0

        for cpunumber in range(self.cpucount):
            cpuname = "/sys/devices/system/cpu/cpu%i/cpufreq" \
                      "/scaling_cur_freq" % cpunumber
            cpufile = open(cpuname)
            clock = int(cpufile.read().rstrip("\n")) / 1000
            self.minimum_frequency = min(self.minimum, clock)
            self.maximum_frequency = max(self.maximum, clock)

            if not self.no_labels:
                self.cpulabels[cpunumber].set_text(str(clock))
            if clock <= self.minimum:
                color = gtk.gdk.Color(0, 65535, 0)
            elif (clock > self.minimum) and (clock < self.medlow):
                color = gtk.gdk.Color(32768, 65535, 0)
            elif (clock > self.medlow) and (clock < self.medhigh):
                color = gtk.gdk.Color(65535, 65535, 0)
            elif (clock > self.medhigh) and (clock < self.maximum):
                color = gtk.gdk.Color(65535, 32768, 0)
            else:
                color = gtk.gdk.Color(65535, 0, 0)

            self.eventboxes[cpunumber].modify_bg(gtk.STATE_NORMAL, color)
            speed += clock

        speed = speed / self.cpucount

        if not self.no_labels:
            self.speedfreq.set_text("%i\n%i\n%i" % (speed, self.minimum_frequency, self.maximum_frequency))
        return True

    def main(self):
        """
        Runs the GTK main loop
        """
        gtk.main()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--count", "-c", help="Specifiy number of cores to "
                                              "inspect (4)",
                        default=4, type=int)

    parser.add_argument("--basefreq", "-b", help="Base frequency (1000)",
                        default=1000, type=int)

    parser.add_argument("--max", "-m", help="Maximum frequency multiplier "
                                            "red (4)",
                        default=4, type=float)
    parser.add_argument("--medhigh", "-mh",
                        help="Medium high frequency multiplier orange (3)",
                        default=3,
                        type=float)
    parser.add_argument("--medlow", "-ml",
                        help="Medium low frequency multiplier yellow (2)",
                        default=2,
                        type=float)
    parser.add_argument("--low", "-l",
                        help="Lowest frequency multiplier green (0.8)",
                        default=0.8, type=float)
    parser.add_argument("--refresh", "-r", help="Refresh interval [ms] (1000)",
                        default=1000, type=int)
    args = parser.parse_args()

    cpuspeed = CPUSpeed(args, parser)
    cpuspeed.main()
